sudo: required
language: node_js
node_js:
- '6'
before_install:
 - gem install sass
 - gem install ruby
 - npm install -g npm
 - npm install promise
before_script:
  - npm install -g gulp
script:
 - gulp deploy
